name: Build and Run AiCodeReview

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install and Copy JAR
        run: |
          # 确保libs目录存在
          mkdir -p ./libs
          
          # 安装JAR到本地Maven仓库
          mvn install:install-file \
          -Dfile=./libs/code-review-sdk-1.0.jar \
          -DgroupId=com.DXG \
          -DartifactId=code-review-sdk \
          -Dversion=1.0 \
          -Dpackaging=jar
          
          # 复制JAR到libs目录（如果需要的话）
          mvn dependency:copy \
          -Dartifact=com.DXG:code-review-sdk:1.0 \
          -DoutputDirectory=./libs

      - name: Run Code Review
        run: java -jar ./libs/code-review-sdk-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
