name: Build and Run AiCodeReview

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Code Review
        run: |
          # 找到生成的JAR文件
          JAR_FILE=$(find . -name "code-review-sdk-*.jar" | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "Error: code-review-sdk JAR file not found"
            exit 1
          fi
          echo "Found JAR file: $JAR_FILE"
          
          # 运行代码审查
          java -jar $JAR_FILE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
